=== jenslammert/experiment-player/lib/experiment-reader/session.dtd
<!-- ==========================================================
		Elements refering to the target transcript structure
     ========================================================== -->

<!ELEMENT session (head, speakers, recording, timeline, greeting, experiment, farewell)>

<!ELEMENT greeting (topic)+>
<!ELEMENT experiment (initial-narrative, last-minute)>
<!ELEMENT farewell (topic)+>

<!ELEMENT initial-narrative (topic+)>
<!ELEMENT last-minute (phase, phase, phase, phase, phase, phase)>

<!ELEMENT phase (topic)+>
<!ATTLIST phase id NMTOKEN #REQUIRED >

<!ELEMENT topic (contribution)+>
<!ATTLIST topic 
	id (bz_1|bz_2|
		i_1|i_2|i_3|i_4|i_5|i_6|i_7|i_8|i_10|i_12|i_14|i_15|i_16|i_17|i_19|i_20|
		lm_1_1|lm_1_2|lm_1_3|lm_1_5|lm_1_6|lm_1_7|lm_1_8|
		lm_2_1|lm_2_4|lm_2_6|lm_2_9|
		lm_2_11|lm_2_13|lm_2_15|lm_2_16|lm_2_17|lm_2_20|
		lm_2_23|lm_2_25|lm_2_27|lm_2_28|lm_2_30|
		lm_2_31|lm_2_38|
		lm_3_1|lm_3_2|lm_3_3|lm_3_4|lm_3_6|lm_3_7|lm_3_8|
		lm_4_1|lm_4_2|lm_4_4|lm_4_6|
		lm_5_1|lm_5_2|lm_5_5|lm_5_7|
		lm_5_19|lm_5_20|
		lm_5_21|lm_5_22|lm_5_24|lm_5_30|
		lm_5_31|lm_5_32|lm_5_33|
		a_6_1|a_6_3|a_6_5|
		v_1) #REQUIRED
>



<!-- ==========================================================
		Elements inspired by Folker-Schema
     ========================================================== -->

<!ELEMENT head ANY>


<!ELEMENT speakers (speaker)*>
<!ELEMENT speaker (#PCDATA|name)*>
<!ATTLIST speaker
	speaker-id ID #REQUIRED
>

<!ELEMENT name (#PCDATA)>

<!ELEMENT recording EMPTY>
<!ATTLIST recording
	path CDATA #IMPLIED
>


<!ELEMENT timeline (timepoint, (timepoint)+)>
<!ELEMENT timepoint EMPTY>
<!ATTLIST timepoint
	timepoint-id ID #REQUIRED
	absolute-time NMTOKEN #REQUIRED
>


<!ELEMENT contribution (#PCDATA|segment|unparsed|breathe|non-phonological|uncertain|pause|time|phrase)*>
<!ATTLIST contribution
	speaker-reference IDREF #IMPLIED
	start-reference IDREF #REQUIRED
	end-reference IDREF #REQUIRED
	parse-level NMTOKEN #IMPLIED
	id (addition|elaboration|removal|repetition|rejection|weight_limit|weight_limit_extended|
	save_comment|make_comment|enumeration|selected_category|remaining_time|acknowledgement) #IMPLIED
>


<!ELEMENT segment (#PCDATA)>
<!ATTLIST segment
	start-reference IDREF #IMPLIED
	end-reference IDREF #IMPLIED
>


<!ELEMENT unparsed (time)*>


<!ELEMENT breathe EMPTY>
<!ATTLIST breathe
	type (in|out) #IMPLIED
	length NMTOKEN #REQUIRED
>


<!ELEMENT non-phonological EMPTY>
<!ATTLIST non-phonological
	description CDATA #REQUIRED
>


<!ELEMENT uncertain (#PCDATA|time|stress|lengthening|alternative)*>


<!ELEMENT alternative (#PCDATA|time|stress|lengthening)*>


<!ELEMENT pause EMPTY>
<!ATTLIST pause
	duration NMTOKEN #REQUIRED
>


<!ELEMENT time EMPTY>
<!ATTLIST time
	timepoint-reference IDREF #REQUIRED
>


<!ELEMENT phrase (#PCDATA|breathe|non-phonological|uncertain|pause|time|stress|lengthening)*>
<!ATTLIST phrase
	type (intonation-phrase|fragment|unaccentuated) #REQUIRED
	boundary-intonation (high-rise|rise|steady|fall|low-fall) #IMPLIED
>


<!ELEMENT stress (time)*>
<!ELEMENT lengthening EMPTY>
<!ATTLIST lengthening
	length NMTOKEN #IMPLIED
>

=== jenslammert/experiment-player/lib/experiment-reader/tests/test-experiment-valid.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE session SYSTEM "session.dtd">

<session>
  <head/>
  <speakers>
    <speaker speaker-id="W">
      <name>Wizard</name>
    </speaker>
    <speaker speaker-id="P">
      <name>Proband</name>
    </speaker>
  </speakers>

  <recording path="test-experiment-valid.wav"/>

  <timeline>
    <timepoint timepoint-id="TLI_0" absolute-time="7.214049251927732"/>
    <timepoint timepoint-id="TLI_1" absolute-time="8.348253519252669"/>
    <timepoint timepoint-id="TLI_2" absolute-time="10.228151350137683"/>
    <timepoint timepoint-id="TLI_3" absolute-time="10.468148330350127"/>
    <timepoint timepoint-id="TLI_4" absolute-time="11.628133734710278"/>
    <timepoint timepoint-id="TLI_5" absolute-time="13.648297524768681"/>
    <timepoint timepoint-id="TLI_6" absolute-time="15.914218445730855"/>
    <timepoint timepoint-id="TLI_7" absolute-time="18.033208622734193"/>
    <timepoint timepoint-id="TLI_8" absolute-time="19.697200908969947"/>
    <timepoint timepoint-id="TLI_9" absolute-time="20.72419614813107"/>
    <timepoint timepoint-id="TLI_10" absolute-time="23.844181684823106"/>
    <timepoint timepoint-id="TLI_11" absolute-time="26.84716776388919"/>
    <timepoint timepoint-id="TLI_12" absolute-time="29.83715390321906"/>
    <timepoint timepoint-id="TLI_13" absolute-time="32.54114136835216"/>
    <timepoint timepoint-id="TLI_14" absolute-time="35.64829780703222"/>
    <timepoint timepoint-id="TLI_15" absolute-time="36.908294160025214"/>
    <timepoint timepoint-id="TLI_16" absolute-time="40.96829190279636"/>
    <timepoint timepoint-id="TLI_17" absolute-time="41.52775751951068"/>
    <timepoint timepoint-id="TLI_18" absolute-time="41.77775437389864"/>
    <timepoint timepoint-id="TLI_19" absolute-time="42.62774367881771"/>
    <timepoint timepoint-id="TLI_20" absolute-time="44.367721785357936"/>
    <timepoint timepoint-id="TLI_21" absolute-time="44.96771423588905"/>
    <timepoint timepoint-id="TLI_22" absolute-time="48.5076696940226"/>
    <timepoint timepoint-id="TLI_23" absolute-time="49.587656104978606"/>
    <timepoint timepoint-id="TLI_24" absolute-time="53.327609046622534"/>
    <timepoint timepoint-id="TLI_25" absolute-time="57.868294100469406"/>
    <timepoint timepoint-id="TLI_26" absolute-time="61.519908309894845"/>
    <timepoint timepoint-id="TLI_27" absolute-time="63.52829612507884"/>
    <timepoint timepoint-id="TLI_28" absolute-time="64.36703373249568"/>
    <timepoint timepoint-id="TLI_29" absolute-time="65.2170174085329"/>
    <timepoint timepoint-id="TLI_30" absolute-time="65.95098649042936"/>
    <timepoint timepoint-id="TLI_31" absolute-time="67.48497937930296"/>
    <timepoint timepoint-id="TLI_32" absolute-time="70.3839659404793"/>
    <timepoint timepoint-id="TLI_33" absolute-time="71.94466128838656"/>
    <timepoint timepoint-id="TLI_34" absolute-time="75.96828798083035"/>
    <timepoint timepoint-id="TLI_35" absolute-time="79.84792206844514"/>
    <timepoint timepoint-id="TLI_36" absolute-time="84.03390266350696"/>
    <timepoint timepoint-id="TLI_37" absolute-time="87.17988807967143"/>
    <timepoint timepoint-id="TLI_38" absolute-time="88.14188362015146"/>
    <timepoint timepoint-id="TLI_39" absolute-time="89.32487813614719"/>
    <timepoint timepoint-id="TLI_40" absolute-time="90.33887343557211"/>
    <timepoint timepoint-id="TLI_41" absolute-time="91.66486728866623"/>
    <timepoint timepoint-id="TLI_42" absolute-time="93.41579885069328"/>
    <timepoint timepoint-id="TLI_43" absolute-time="94.49329519655608"/>
    <timepoint timepoint-id="TLI_44" absolute-time="94.66804448950987"/>
    <timepoint timepoint-id="TLI_45" absolute-time="97.15084185734972"/>
    <timepoint timepoint-id="TLI_46" absolute-time="98.94303316519402"/>
    <timepoint timepoint-id="TLI_47" absolute-time="100.68682546560069"/>
    <timepoint timepoint-id="TLI_48" absolute-time="103.5430209799653"/>
    <timepoint timepoint-id="TLI_49" absolute-time="106.2637996124377"/>
    <timepoint timepoint-id="TLI_50" absolute-time="109.09300627822196"/>
    <timepoint timepoint-id="TLI_51" absolute-time="111.56777502481417"/>
    <timepoint timepoint-id="TLI_52" absolute-time="113.76799389432104"/>
    <timepoint timepoint-id="TLI_53" absolute-time="115.11799031822129"/>
    <timepoint timepoint-id="TLI_54" absolute-time="117.76798329846997"/>
    <timepoint timepoint-id="TLI_55" absolute-time="118.28048194087654"/>
    <timepoint timepoint-id="TLI_56" absolute-time="120.16797694095935"/>
    <timepoint timepoint-id="TLI_57" absolute-time="120.49297608004643"/>
    <timepoint timepoint-id="TLI_58" absolute-time="122.86796978875986"/>
    <timepoint timepoint-id="TLI_59" absolute-time="128.01829794257122"/>
    <timepoint timepoint-id="TLI_60" absolute-time="129.71309701995418"/>
    <timepoint timepoint-id="TLI_61" absolute-time="131.83468107357612"/>
    <timepoint timepoint-id="TLI_62" absolute-time="133.4206737213946"/>
    <timepoint timepoint-id="TLI_63" absolute-time="136.1506610660001"/>
    <timepoint timepoint-id="TLI_64" absolute-time="139.36164618084567"/>
    <timepoint timepoint-id="TLI_65" absolute-time="142.1566332241323"/>
    <timepoint timepoint-id="TLI_66" absolute-time="143.98962472693887"/>
    <timepoint timepoint-id="TLI_67" absolute-time="145.8429089288403"/>
    <timepoint timepoint-id="TLI_68" absolute-time="147.36790488917208"/>
    <timepoint timepoint-id="TLI_69" absolute-time="149.21830281955513"/>
    <timepoint timepoint-id="TLI_70" absolute-time="152.49714766571643"/>
    <timepoint timepoint-id="TLI_71" absolute-time="154.64330065593106"/>
    <timepoint timepoint-id="TLI_72" absolute-time="160.64286972419137"/>
    <timepoint timepoint-id="TLI_73" absolute-time="161.76786674410826"/>
    <timepoint timepoint-id="TLI_74" absolute-time="166.36785455887954"/>
    <timepoint timepoint-id="TLI_75" absolute-time="167.9745135402589"/>
    <timepoint timepoint-id="TLI_76" absolute-time="169.87250474174652"/>
    <timepoint timepoint-id="TLI_77" absolute-time="171.2504983537855"/>
    <timepoint timepoint-id="TLI_78" absolute-time="173.01783694327716"/>
    <timepoint timepoint-id="TLI_79" absolute-time="177.56830096345422"/>
    <timepoint timepoint-id="TLI_80" absolute-time="180.6624547228065"/>
    <timepoint timepoint-id="TLI_81" absolute-time="182.9172980245914"/>
    <timepoint timepoint-id="TLI_82" absolute-time="184.31680603608694"/>
    <timepoint timepoint-id="TLI_83" absolute-time="185.09280495705175"/>
    <timepoint timepoint-id="TLI_84" absolute-time="192.44278548717543"/>
    <timepoint timepoint-id="TLI_85" absolute-time="195.19277820252785"/>
    <timepoint timepoint-id="TLI_86" absolute-time="195.6677769442705"/>
    <timepoint timepoint-id="TLI_87" absolute-time="197.75737547593158"/>
    <timepoint timepoint-id="TLI_88" absolute-time="201.21776224252716"/>
    <timepoint timepoint-id="TLI_89" absolute-time="201.9177603882532"/>
    <timepoint timepoint-id="TLI_90" absolute-time="205.5427507857632"/>
    <timepoint timepoint-id="TLI_91" absolute-time="206.44274840169672"/>
    <timepoint timepoint-id="TLI_92" absolute-time="208.78132437224343"/>
    <timepoint timepoint-id="TLI_93" absolute-time="210.87431466977435"/>
    <timepoint timepoint-id="TLI_94" absolute-time="212.76773164700722"/>
    <timepoint timepoint-id="TLI_95" absolute-time="215.67129243243838"/>
    <timepoint timepoint-id="TLI_96" absolute-time="216.51830764934473"/>
    <timepoint timepoint-id="TLI_97" absolute-time="218.54330228519513"/>
    <timepoint timepoint-id="TLI_98" absolute-time="218.9177153558862"/>
    <timepoint timepoint-id="TLI_99" absolute-time="220.9667089516016"/>
    <timepoint timepoint-id="TLI_100" absolute-time="223.7177026408649"/>
    <timepoint timepoint-id="TLI_101" absolute-time="224.4927005879188"/>
    <timepoint timepoint-id="TLI_102" absolute-time="225.31769840252448"/>
    <timepoint timepoint-id="TLI_103" absolute-time="227.71769204501385"/>
    <timepoint timepoint-id="TLI_104" absolute-time="230.91768356833302"/>
    <timepoint timepoint-id="TLI_105" absolute-time="235.46829931972786"/>
    <timepoint timepoint-id="TLI_106" absolute-time="238.62918600659725"/>
    <timepoint timepoint-id="TLI_107" absolute-time="239.9811797391638"/>
    <timepoint timepoint-id="TLI_108" absolute-time="242.0741700366947"/>
    <timepoint timepoint-id="TLI_109" absolute-time="243.95916129844613"/>
    <timepoint timepoint-id="TLI_110" absolute-time="245.54515394626458"/>
    <timepoint timepoint-id="TLI_111" absolute-time="247.69329830992396"/>
    <timepoint timepoint-id="TLI_112" absolute-time="250.9676304566296"/>
    <timepoint timepoint-id="TLI_113" absolute-time="252.89262535737623"/>
    <timepoint timepoint-id="TLI_114" absolute-time="253.47511718535685"/>
    <timepoint timepoint-id="TLI_115" absolute-time="255.36661782728243"/>
    <timepoint timepoint-id="TLI_116" absolute-time="257.89509669567053"/>
    <timepoint timepoint-id="TLI_117" absolute-time="258.701092959316"/>
    <timepoint timepoint-id="TLI_118" absolute-time="259.14260880135896"/>
    <timepoint timepoint-id="TLI_119" absolute-time="260.2926057550518"/>
    <timepoint timepoint-id="TLI_120" absolute-time="261.99260125181513"/>
    <timepoint timepoint-id="TLI_121" absolute-time="263.59259701347474"/>
    <timepoint timepoint-id="TLI_122" absolute-time="264.2425952916489"/>
    <timepoint timepoint-id="TLI_123" absolute-time="265.5925917155492"/>
    <timepoint timepoint-id="TLI_124" absolute-time="265.86759098708444"/>
    <timepoint timepoint-id="TLI_125" absolute-time="268.2675846295738"/>
    <timepoint timepoint-id="TLI_126" absolute-time="274.0675692655898"/>
    <timepoint timepoint-id="TLI_127" absolute-time="274.94256694774737"/>
    <timepoint timepoint-id="TLI_128" absolute-time="284.8925405905678"/>
    <timepoint timepoint-id="TLI_129" absolute-time="287.00196176506"/>
    <timepoint timepoint-id="TLI_130" absolute-time="289.5239500738861"/>
